- name: Deploy to Tomcat
  hosts: web
  become: yes
  tasks:

    - name: Copy WAR file to Tomcat
      copy:
        src: "/var/snap/jenkins/5042/workspace/MyMavenAnsibleApp01/target/MyMavenAnsibleApp01.war"
        dest: "/opt/tomcat/webapps/MyMavenAnsibleApp01.war"
        remote_src: no

   
